import type { Metadata } from "next";
import 'flowbite';
import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "./menu"; 
import Footer from "./footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={`${inter.className} bg-secondary`}>
        {children}
      </body>
    </html>
  );
}
